### ISSUE TITLE
Add hosted website URL in repo details and readme

### ISSUE THREAD

**Issue by arunvelsriram** [parasoft/parabank#40]
The hosted demo website URL https://parabank.parasoft.com/parabank/index.htm could be mentioned in repo details section and readme for users to access it easily.

**Comment by benken-parasoft** [comment]
We intentionally do not reference the "parabank.parasoft.com" host anywhere including in any official Parasoft product documentation.  Instead, users are encouraged to deploy ParaBank on their own host, like on their local machine.  You have various options:

- Build with Maven (`mvn -DskipTests clean package`) then copy the `target/parabank.war` to your own Tomcat installation.
- Use cargo-maven3-plugin to automatically provision a Tomcat: `mvn -DskipTests clean package cargo:run`
- Run the official [parasoft/parabank](https://hub.docker.com/r/parasoft/parabank) Docker image.
- If using Parasoft SOAtest or Parasoft Virtualize then you can also create a "ParaBank Example Project" directly within the tool.

For now, the "parabank.parasoft.com" host is available as a convenience but since it is shared on the open Internet there are no guarantees about the state.  Accounts, account balances, login credentials, etc. can unexpectedly change at any time.  The deployment also periodically shuts down to reset and restart itself.  If you need to use ParaBank for something at least semi-important then you should always deploy ParaBank on your own host so that you have control over the state.

**Comment by arunvelsriram** [comment]
Yes agree that users should deploy their own instance for their testing.

My intention for the link is for users to just navigate and explore the demo app to see if this is what they were looking for and understanding the capabilities of the app. This will reduce the feedback loop for the users to decide if this app will solve their use case.

May be we could explicitly mention in readme that the hosted site will be unstable and users are encouraged to deploy their own instance.
